{
 "title": "Enhanced Backup Overview",
 "description": "Restic statistics dashboard with enhanced metrics",
 "tags": [ "system" ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Repository Check",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "restic_check_success" }
   ]
  },
  {
   "title": "Repository Locks",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "restic_locks_total" }
   ]
  },
  {
   "title": "Total Snapshots in Repository",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "restic_snapshots_total" }
   ]
  },
  {
   "title": "Oldest Backup Age (Days)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "restic_retention_oldest_backup_age_seconds / 86400",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Last backup",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "last_over_time(max by(client_hostname, snapshot_tag) (restic_backup_timestamp)[30m:]) * 1000",
     "legendFormat": "{{client_hostname}}"
    },
    {
     "expr": "time() - last_over_time(max by(client_hostname, snapshot_tag) (restic_backup_timestamp)[30m:])",
     "legendFormat": "{{client_hostname}}"
    }
   ]
  },
  {
   "title": "Total snapshot count per host",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max by(client_hostname, snapshot_tag) (restic_backup_snapshots_total)",
     "legendFormat": "{{client_hostname}}"
    }
   ]
  },
  {
   "title": "Total backup size over time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max by(client_hostname, snapshot_tag) (restic_backup_size_total)",
     "legendFormat": "{{client_hostname}} - {{snapshot_tag}}"
    }
   ]
  },
  {
   "title": "Total backup files over time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max by(client_hostname, snapshot_tag) (restic_backup_files_total)",
     "legendFormat": "{{client_hostname}} - {{snapshot_tag}}"
    }
   ]
  },
  {
   "title": "Total snapshot count over time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max by(client_hostname, snapshot_tag) (restic_backup_snapshots_total)",
     "legendFormat": "{{client_hostname}} - {{snapshot_tag}}"
    }
   ]
  },
  {
   "title": "Backup directories over time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "restic_backup_dirs_total",
     "legendFormat": "{{client_hostname}} - {{snapshot_tag}}"
    }
   ]
  },
  {
   "title": "Total backup size, files & dirs",
   "type": "table",
   "gridPos": { "h": 9, "w": 18, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "last_over_time(max by(client_hostname, snapshot_tag) (restic_backup_size_total)[30m:])",
     "legendFormat": "{{client_hostname}}"
    },
    {
     "expr": "last_over_time(max by(client_hostname, snapshot_tag) (restic_backup_files_total)[30m:])",
     "legendFormat": "{{client_hostname}}"
    },
    {
     "expr": "last_over_time(max by(client_hostname, snapshot_tag) (restic_backup_dirs_total)[30m:])",
     "legendFormat": "{{client_hostname}}"
    }
   ]
  },
  {
   "title": "Average files per directory",
   "type": "table",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max by(client_hostname, snapshot_tag) (restic_backup_files_per_dir)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Backup paths count over time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "restic_backup_paths_count",
     "legendFormat": "{{client_hostname}} - {{snapshot_tag}}"
    }
   ]
  },
  {
   "title": "Backup age over time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "restic_backup_age_seconds",
     "legendFormat": "{{client_hostname}} - {{snapshot_tag}}"
    }
   ]
  },
  {
   "title": "Backups by Period",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "restic_backups_by_period_total", "legendFormat": "{{period}} backups" }
   ]
  },
  {
   "title": "Retention Policy Coverage",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "restic_retention_policy_coverage_days",
     "legendFormat": "{{retention_type}} retention coverage"
    }
   ]
  },
  {
   "title": "Retention Maximum Age by Type",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "restic_retention_max_age_seconds",
     "legendFormat": "{{retention_type}} retention max age"
    }
   ]
  },
  {
   "title": "Total Backup Coverage Span (Days)",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "restic_retention_age_span_seconds / 86400",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Scrape Duration",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "restic_scrape_duration_seconds", "legendFormat": "__auto" }
   ]
  }
 ]
}